### ISSUE TITLE
koodikatselmointi

### ISSUE THREAD

**Issue by Muisku** [kate187/ot-harjoitustyo#1]
Päivä ja kellonaika: 22.30 | 10.12.2019

Yleinen
Peli tuntuu toimivan kuten vaatimusmäärittelyssä kerrotaan. En onnistunut kaatamaan ohjelmaa, tämä siis hyvä! Koodi oli mielenkiintoista tutkittavaa, metodit oltiin rakennettu selkeästi eikä mitään täysin outoa tullut vastaan missään. 

Arkkitehtuuri
Kaikki ohjelman luokat ovat saman kansion alla. Voisi olla selkeämpää jatkokehittäjää ajatellen, jos luokat olisi jaoteltu eri kansioihin.

Testit
Testejä oltiin tehty vain pääluokalle App.java. Ohjelmassa on monta luokkaa joita oltaisiin voitu testata. Kaikki kuusi testiä toimivat.

**Comment by kate187** [comment]
Kiitos kommentoinnista.

Jaoin pelikoodin eri pakkauksiin nykyiseen versioon. Nyt arkkitehtuuri vastaa enemmän Java-ohjelmaa.

"Testejä oltiin tehty vain pääluokalle App.java." Tarkempi vilaisu olisi osoittanut, ettei tämä pidä paikkaansa.
